--------------------------------------------------------
-- Schema STAGING
--------------------------------------------------------
CREATE SCHEMA "STAGING";
SET SCHEMA 'STAGING';

--------------------------------------------------------
-- Table "STAGING".DWHS_D_CUSTOMERS
--------------------------------------------------------
CREATE TABLE "STAGING".DWHS_D_CUSTOMERS
(    
    CUSTOMER_UNIQUE_ID VARCHAR(50), 
    CUSTOMER_ZIPCODE VARCHAR(5), 
    CUSTOMER_CITY VARCHAR(50), 
    CUSTOMER_STATE VARCHAR(5),
    CUSTOMER_GEO_LAT DOUBLE PRECISION, 
    CUSTOMER_GEO_LONG DOUBLE PRECISION,
    UPD_FLAG VARCHAR(1)
);
--------------------------------------------------------
-- Table "STAGING".DWHS_D_PAYMENTS
--------------------------------------------------------
CREATE TABLE "STAGING".DWHS_D_ORDER_PAYMENTS
(    
    ORDER_ID VARCHAR(50), 
    PAYMENT_SEQUENTIAL INTEGER, 
    PAYMENT_TYPE VARCHAR(20),
    PAYMENT_INSTALLMENTS INTEGER,
    PAYMENT_VALUE REAL,
    UPD_FLAG VARCHAR(1)
);
--------------------------------------------------------
-- Table "STAGING".DWHS_F_ORDERS
--------------------------------------------------------
CREATE TABLE "STAGING".DWHS_F_ORDERS
(    
    ORDER_ID VARCHAR(50),
    CUSTOMER_UNIQUE_ID VARCHAR(50), 
    PRODUCT_ID VARCHAR(50),
    SELLER_ID VARCHAR(50),
    ORDER_ITEM_QTA INTEGER, 
    PRICE REAL,
    FREIGHT_VALUE REAL,
    ORDER_STATUS VARCHAR(30),
    REVIEW_SCORE INTEGER, 
    ORDER_PURCHASE_TIMESTAMP TIMESTAMP,
    ORDER_APPROVAL_TIMESTAMP TIMESTAMP,
    ORDER_DELIVERED_CARRIER_TIMESTAMP TIMESTAMP,
    ORDER_DELIVERED_CUSTOMER_TIMESTAMP TIMESTAMP,
    ORDER_ESTIMATED_DELIVERY_TIMESTAMP TIMESTAMP,
    UPD_FLAG VARCHAR(1)
);
--------------------------------------------------------
-- Table "STAGING".DWHS_D_PRODUCTS
--------------------------------------------------------
CREATE TABLE "STAGING".DWHS_D_PRODUCTS
(    
    PRODUCT_ID VARCHAR(50),
    PRODUCT_CATEGORY_NAME VARCHAR(100), 
    PRODUCT_CATEGORY_NAME_ENGLISH VARCHAR(100),
    PRODUCT_NAME_LENGHT INTEGER,
    DESCRIPTION_LENGHT INTEGER,
    PRODUCT_PHOTO_QTA INTEGER,
    PRODUCT_WEIGHT_GRAMS INTEGER,
    PRODUCT_LENGHT_CM INTEGER,
    PRODUCT_HEIGHT_CM INTEGER,
    PRODUCT_WIDTH_CM INTEGER,
    UPD_FLAG VARCHAR(1)
);
--------------------------------------------------------
-- Table "STAGING".DWHS_D_SELLERS
--------------------------------------------------------
CREATE TABLE "STAGING".DWHS_D_SELLERS
(
    SELLER_ID VARCHAR(50),
    SELLER_ZIPCODE VARCHAR(5),
    SELLER_CITY VARCHAR(50), 
    SELLER_STATE VARCHAR(5),
    SELLER_GEO_LAT DOUBLE PRECISION, 
    SELLER_GEO_LONG DOUBLE PRECISION, 
    UPD_FLAG VARCHAR(1)
);

--------------------------------------------------------
-- Table "STAGING".ERROR_D_CUSTOMERS
--------------------------------------------------------
CREATE TABLE "STAGING".ERROR_D_CUSTOMERS
(    
    CUSTOMER_UNIQUE_ID VARCHAR(50), 
    CUSTOMER_ZIPCODE VARCHAR(5), 
    CUSTOMER_CITY VARCHAR(50), 
    CUSTOMER_STATE VARCHAR(5),
    CUSTOMER_GEO_LAT DOUBLE PRECISION, 
    CUSTOMER_GEO_LONG DOUBLE PRECISION,
    LOGT TIMESTAMP
);
--------------------------------------------------------
-- Table "STAGING".ERROR_ORDER_PAYMENTS
--------------------------------------------------------
CREATE TABLE "STAGING".ERROR_D_ORDER_PAYMENTS
(    
    ORDER_ID VARCHAR(50), 
    PAYMENT_SEQUENTIAL INTEGER, 
    PAYMENT_TYPE VARCHAR(20),
    PAYMENT_INSTALLMENTS INTEGER,
    PAYMENT_VALUE REAL,
    LOGT TIMESTAMP
);
--------------------------------------------------------
-- Table "STAGING".ERROR_F_ORDERS
--------------------------------------------------------
CREATE TABLE "STAGING".ERROR_F_ORDERS
(    
    ORDER_ID VARCHAR(50),
    CUSTOMER_UNIQUE_ID VARCHAR(50), 
    PRODUCT_ID VARCHAR(50),
    SELLER_ID VARCHAR(50),
    ORDER_ITEM_QTA INTEGER, 
    PRICE REAL,
    FREIGHT_VALUE REAL,
    ORDER_STATUS VARCHAR(30),
    REVIEW_SCORE INTEGER, 
    ORDER_PURCHASE_TIMESTAMP TIMESTAMP,
    ORDER_APPROVAL_TIMESTAMP TIMESTAMP,
    ORDER_DELIVERED_CARRIER_TIMESTAMP TIMESTAMP,
    ORDER_DELIVERED_CUSTOMER_TIMESTAMP TIMESTAMP,
    ORDER_ESTIMATED_DELIVERY_TIMESTAMP TIMESTAMP,
    LOGT TIMESTAMP
);
--------------------------------------------------------
-- Table "STAGING".ERROR_D_PRODUCTS
--------------------------------------------------------
CREATE TABLE "STAGING".ERROR_D_PRODUCTS
(    
    PRODUCT_ID VARCHAR(50),
    PRODUCT_CATEGORY_NAME VARCHAR(100), 
    PRODUCT_CATEGORY_NAME_ENGLISH VARCHAR(100),
    PRODUCT_NAME_LENGHT INTEGER,
    DESCRIPTION_LENGHT INTEGER,
    PRODUCT_PHOTO_QTA INTEGER,
    PRODUCT_WEIGHT_GRAMS INTEGER,
    PRODUCT_LENGHT_CM INTEGER,
    PRODUCT_HEIGHT_CM INTEGER,
    PRODUCT_WIDTH_CM INTEGER,
    LOGT TIMESTAMP
);
--------------------------------------------------------
-- Table "STAGING".ERROR_D_SELLERS
--------------------------------------------------------
CREATE TABLE "STAGING".ERROR_D_SELLERS
(
    SELLER_ID VARCHAR(50),
    SELLER_ZIPCODE VARCHAR(5),
    SELLER_CITY VARCHAR(50), 
    SELLER_STATE VARCHAR(5),
    SELLER_GEO_LAT DOUBLE PRECISION, 
    SELLER_GEO_LONG DOUBLE PRECISION, 
    LOGT TIMESTAMP
);
